version: '3'
services:
  mysql-db:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=neeraj
      - MYSQL_DATABASE=demo
  web-app:
    build: .
    ports:
      - "8080:8080"